# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: capistrano-git-submodule-strategy 0.1.23 ruby lib

Gem::Specification.new do |s|
  s.name = "capistrano-git-submodule-strategy".freeze
  s.version = "0.1.23"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze) if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib".freeze]
  s.authors = ["Boris Gorbylev".freeze]
  s.date = "2016-12-15"
  s.description = "Git submodule support for Capistrano 3.0-3.6. For Capistrano 3.7+ use new plugin https://github.com/ekho/capistrano-git-with-submodules".freeze
  s.email = "ekho@ekho.name".freeze
  s.extra_rdoc_files = [
    "LICENSE",
    "README.md"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE",
    "README.md",
    "Rakefile",
    "VERSION",
    "capistrano-git-submodule-strategy.gemspec",
    "lib/capistrano-git-submodule-strategy.rb",
    "lib/capistrano/git-submodule-strategy.rb",
    "test/helper.rb",
    "test/test_capistrano-git-local.rb"
  ]
  s.homepage = "http://github.com/ekho/capistrano-git-submodule-strategy".freeze
  s.licenses = ["MIT".freeze]
  s.rubygems_version = "2.5.2".freeze
  s.summary = "Git submodule support for Capistrano 3.0-3.6".freeze

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<shoulda>.freeze, [">= 0"])
      s.add_development_dependency(%q<rdoc>.freeze, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>.freeze, ["~> 1.0"])
      s.add_development_dependency(%q<mini_portile2>.freeze, ["~> 2.1"])
      s.add_development_dependency(%q<jeweler>.freeze, ["~> 2.3"])
      s.add_development_dependency(%q<simplecov>.freeze, [">= 0"])
      s.add_runtime_dependency(%q<capistrano>.freeze, ["< 3.7", ">= 3.1.0"])
    else
      s.add_dependency(%q<shoulda>.freeze, [">= 0"])
      s.add_dependency(%q<rdoc>.freeze, ["~> 3.12"])
      s.add_dependency(%q<bundler>.freeze, ["~> 1.0"])
      s.add_dependency(%q<mini_portile2>.freeze, ["~> 2.1"])
      s.add_dependency(%q<jeweler>.freeze, ["~> 2.3"])
      s.add_dependency(%q<simplecov>.freeze, [">= 0"])
      s.add_dependency(%q<capistrano>.freeze, ["< 3.7", ">= 3.1.0"])
    end
  else
    s.add_dependency(%q<shoulda>.freeze, [">= 0"])
    s.add_dependency(%q<rdoc>.freeze, ["~> 3.12"])
    s.add_dependency(%q<bundler>.freeze, ["~> 1.0"])
    s.add_dependency(%q<mini_portile2>.freeze, ["~> 2.1"])
    s.add_dependency(%q<jeweler>.freeze, ["~> 2.3"])
    s.add_dependency(%q<simplecov>.freeze, [">= 0"])
    s.add_dependency(%q<capistrano>.freeze, ["< 3.7", ">= 3.1.0"])
  end
end

